### ISSUE TITLE
cant login in with minecraft bedrock windows 10 edition

### ISSUE THREAD

**Issue by radmanplays** [ViaVersion/ViaFabricPlus#159]
### General Information

viafabricplus, fabricapi , etc

### Bug Description

i tryed loggingin to my minecraft bedrock windows 10 account on this mod but the code that it gave me was for nintendo switch which i dont own  

### Steps to Reproduce

1.go on settings
2.go on the minecraft bedrock section
3.click login with bedrock account
4.if you dont own minecraft for nintendo switch and only own minecraft for windows 10 it gives an error

### Expected Behavior

i should login to my minecraft for windows 10 account

**Comment by FlorianMichael** [comment]
You don't have to "own" Minecraft for Nintendo switch, the authentication library used for that only uses the Nintendo Switch AzureApp to authenticate, the Microsoft account you log in with doesn't even have to have Minecraft at all, you can just use any Microsoft Account since the ownership checks only apply to the Microsoft Store when you install the Bedrock edition
