### ISSUE TITLE
Hypixel: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(28) + length(4) exceeds writerIndex(28): PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 256)

### ISSUE THREAD

**Issue by road2react** [ViaVersion/ViaFabricPlus#234]
### General Information

ViaFabricPlus, Fabric API, Custom mod (used for debugging this issue)

### Bug Description

When blocks are placed very quickly, a block that would normally play a sound causes a disconnect.

![image](https://github.com/ViaVersion/ViaFabricPlus/assets/93143714/c9f19b89-e31a-46ed-bcaa-c200b1170a53)

### Steps to Reproduce

1. Join Hypixel 1.8.9
2. Place blocks very quickly in a Bed Wars game

To debug, cancel ClientConnection.exceptionCaught and replace with a print statement. Then, placing blocks very quickly will cause many log messages to be printed.

### Expected Behavior

The game should not disconnect

**Comment by FlorianMichael** [comment]
Hi, thanks for you report and sorry for the delayed response.

How do the errors look like without your custom mod? You can't just change the exceptionCaught() in ViaVersion because we throw exceptions internally to cancel packet handling. 

I added a setting in ViaFabricPlus -> General in the meantime: "Ignore packet translation errors", try setting it to "Cancel and notify" and see what happens.

 It would also be good if you try if the same issue happens with ViaProxy, so we know which project it is internally.

**Comment by FlorianMichael** [comment]
Closing this due inactivity, if anyone has updates to this, I'll reopen the issue
