### ISSUE TITLE
Villagers' Trade Options Disappeared When Connectting to an 1.20.2 server with 1.20.1 Client

### ISSUE THREAD

**Issue by Hexona69** [ViaVersion/ViaFabricPlus#262]
### General Information

Tested version
- Minecraft 1.20.1, Fabric 0.14.22. Fabric API 0.88.1, ViaFabricPlus 2.8.7
- Minecraft 1.20.1, Fabric 0.14.23. Fabric API 0.89.3, ViaFabricPlus 2.8.7

### Bug Description

Villagers won't show any trade options and players are therefore not able to trade.

### Steps to Reproduce

1. Download the official Minecraft 1.20.2 server from [here](https://www.minecraft.net/en-us/download/server) and set it up.
2. Connect to the server using a client with ViaFabricPlus 2.8.7.
3. Spawn a villager and place a profession block.
4. The villager won't show any trade options and players won't be able to trade.

### Expected Behavior

The villagers should show their trade options and players should be able to trade.

**Comment by FlorianMichael** [comment]
Hi, the issue has been already fixed in ViaBackwards, you can download the latest ViaBackwards and ViaVersion dev jar file from [ci.viaversion.com](https://ci.viaversion.com/), and in your .minecraft folder in the ViaFabricPlus folder make a "jars" folder where you put both jar files, after that the issue should be fixed.
