### ISSUE TITLE
Connecting to Bedrock times out

### ISSUE THREAD

**Issue by Noxillio** [ViaVersion/ViaFabricPlus#396]
### General Information

https://dump.viaversion.com/fa924240d0bd2058b6851cfc6c774a4e6fd5ece9fb399f204538d8e1e5b061a2

### Bug Description

I am unable to connect to any Bedrock server using this mod. Both servers I tried are running 1.20.70. When attempting to connect, this is all that gets logged to console:

```
[10:53:48] [Render thread/INFO]:
 Connecting to play.applemc.fun, 19132
[10:53:48] [Server Connector #4/INFO]:
 Authenticating with Minecraft Services...
[10:53:49] [Server Connector #4/INFO]:
 Got MC Chain, name: {MINECRAFT_USERNAME}, uuid: {UUID}, xuid: {XUID}
```
(I have redacted my UUID and XUID)

The timeout message is not shown in console. It only appears in-game:
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/40806092/1c04f039-d141-4734-b88d-608b1f0a48e6)

I have tried this from two different computers on separate networks and the same issue occurs. I've also tried using the latest release and the latest successful build artifact.

### Steps to Reproduce

1. Add a Bedrock server.
2. Set version to Bedrock 1.20.70.
3. Attempt to join the server.

### Expected Behavior

The client connects to the server successfully.

**Comment by RaphiMC** [comment]
The server's firewall/proxy seems to block/detect connections from the used Bedrock RakNet library (https://github.com/CloudburstMC/Network).
Sadly the used RakNet library has a lot of issues which aren't getting fixed by the devs of it, so this will remain broken for the time being. (There is a workaround for this, but its more complicated to set up than ViaFabricPlus)

**Comment by Noxillio** [comment]
In that case, please correct me if I'm wrong, but it appears that as of last week they are working on a fix.

**Comment by RaphiMC** [comment]
They library devs are not working on a fix for the connection issues. There are still 4 unsolved issues regarding connection issues to servers and they have been open for almost a year

**Comment by FlorianMichael** [comment]
We have a [ViaProxy](https://github.com/ViaVersion/ViaProxy) plugin implementing alternative RakNet libraries which have fixed this issue, see [here](https://github.com/ViaVersionAddons/ViaProxyRakNetProviders). I'll therefore close the issue for now as I don't plan on adding the plugin into ViaFabricPlus (unless for now since bedrock support is still in alpha state) and recommend you to use ViaProxy (which is the recommended ViaBedrock platform) instead.
