### ISSUE TITLE
Backport needed

### ISSUE THREAD

**Issue by OoSparkleoO** [ViaVersion/ViaFabricPlus#443]
### Problem Description

We need a Backport version on 1.20.4. Because many mod are still on 1.20.4, no 1.20.6+. It can be fatal, especially to redstone player. It is hard do to anything without these mod. So we need the help of ViaFabricPlus. Because of the protocol problem, we can't join 1.20.1 servers with 1.20.4 Minecraft. Plese make a backward fix.

### Solution Description

Plese make a backward fix.

**Comment by Kichura** [comment]
1. Enza has decided that no further 1.20.4 updates will be pushed onto modrinth itself but you can compile the `backport/1.20.4` branch yourself which contains 4.10.3-snapshot support if required,
2. Since you're referring to 1.20.1 server <- 1.20.4 client, normal ViaFabric is available for that as an alternative.

**Comment by OoSparkleoO** [comment]
But it has bugs too :( I'm very sure I have used the latest version.
![image](https://github.com/ViaVersion/ViaFabricPlus/assets/172111169/c68fa97a-3269-460e-a38b-235e94dc20ff)

**Comment by FlorianMichael** [comment]
The 1.20.4 VFP version doesn't provide any fixes for 1.20.6+, meaning you can just use the ViaProxy for joining 1.20.6 servers https://github.com/ViaVersion/ViaProxy
