### ISSUE TITLE
Water/Lava disappears

### ISSUE THREAD

**Issue by fluxo47** [ViaVersion/ViaFabricPlus#451]
### General Information

https://github.com/ViaVersion/ViaFabricPlus/assets/116904446/54abde46-cf4e-43c9-96be-895a57420f3e

### Bug Description

When I use a water/lava bucket on server 1.21 (joined from 1.20.6), the water/lava disappears. Also, the boat does not get placed. 

### Steps to Reproduce

1. Join a 1.21 server from 1.20.6
2. Take a water or lava bucket and fill it with water.
3. Try to place the water or lava bucket.

### Expected Behavior

The water or lava should be placed.

**Comment by FlorianMichael** [comment]
This is a ViaBackwards bug which I fixed lately, you can update ViaVersion/ViaBackwards locally by downloading it from here: 
https://ci.viaversion.com/job/ViaVersion/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/

Then opening your .minecraft folder (or the folder your mods folder is located) and put the jars into config/viafabricplus/jars

**Comment by FlorianMichael** [comment]
You need to put ViaVersion/ViaBackwards into the folder provided in my answer and not into the mods folder / or on the server.

**Comment by FlorianMichael** [comment]
The current jars aren't working anymore due to API breaking changes, you need the jars from the time of my response or you should update to 1.21 and use latest ViaFabricPlus

(Not tested but these should work)
https://ci.viaversion.com/job/ViaVersion/858/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/434/

I am also going to lock conversation on this GH issue for now as these messages are unrelated and spamming the original author, please make your own GitHub issue for further issues.
