### ISSUE TITLE
[Feature request] Automatic Unicode toggle on pre-1.13 servers

### ISSUE THREAD

**Issue by Felix14-v2** [ViaVersion/ViaFabricPlus#511]
### Problem Description

Minecraft 1.12.2 (and older versions) uses "thin" text style (at least in Russian language, other languages may also be affected) which is available by toggling Unicode in the language settings. Because of the difference between old and new font, all text formatting and styling is broken on pre-1.13 servers.

### Solution Description

The easiest solution would be toggling Unicode automatically when connecting to a server with the affected version if affected language is detected on the client.

### Alternatives

I don't think reimplementing the entire font system would be a good alternative.

### Additional Info

_Screenshots will be added later_

**Comment by FlorianMichael** [comment]
Thanks for the suggestion!
Implemented as "Force Unicode font for non-ASCII languages" in the visual category.

**Comment by Felix14-v2** [comment]
> Implemented as "Force Unicode font for non-ASCII languages" in the visual category

This will be disabled by default?

**Comment by FlorianMichael** [comment]
I generally don't think servers should depend on the client having a specific font dimension, this breaks resourcepacks and is overall unsafe. Also unicode font looks worse than the normal one and users shouldn't be forced to it by default (assuming most servers don't depend on the client having unicode enabled)

**Comment by Felix14-v2** [comment]
> assuming most servers don't depend on the client having unicode enabled

The thing is that my language didn't have a "normal" font below 1.13, only the Unicode one. So all servers that still require 1.12.2 client are assuming that their clients only have the Unicode font

**Comment by FlorianMichael** [comment]
I'm still against it because the server can't expect:
- every user having the same language selected
- no one to change the chat width in settings (in the example you provided on discord this would matter)
- not having custom resourcepacks replacing the font installed

Furthermore not every server might depend on that and will break.

I could also imagine many people (especially russians) to use modern versions because the font rendering properly supports their language, unicode font is just worse imo.

I'm open for discussion but right now I see more arguments against it then for it, maybe other affected people can share their opinion.

**Comment by Felix14-v2** [comment]
> Furthermore not every server might depend on that and will break
Maybe then allow server-specific configuration?

**Comment by FlorianMichael** [comment]
Why though? The setting is already included, the only thing is that someone who wants it has to enable it once and after that it will stay enabled

**Comment by Felix14-v2** [comment]
As you said, not all old servers explicitly expect the old font, but the current approach enables it globally

**Comment by FlorianMichael** [comment]
I see your point but I am still unsure if that's really needed, you are the first one even reporting this after over a year and it's not that hard to manually use Minecraft's option.
