### ISSUE TITLE
Game crash when click MP button

### ISSUE THREAD

**Issue by AuthenTiiq** [ViaVersion/ViaFabricPlus#522]
### General Information

Crash reports : https://mclo.gs/LOaMyiN

### Bug Description

Hello,

My games crash when I click the "Multiplayer" button with the ViaFabricPlus mod. 
When I remove the mod, it works.

### Steps to Reproduce

Launch the game,
Click "Multiplayer"

### Expected Behavior

Open the multiplayer menu 😐

**Comment by FlorianMichael** [comment]
Please provide the full client log, I can't reproduce your issue.

**Comment by AuthenTiiq** [comment]
The latest log file : https://mclo.gs/cA2LoFp

**Comment by FlorianMichael** [comment]
Try without any other mods installed, this is most likely a mod incompatibility.

**Comment by AuthenTiiq** [comment]
Good news! It's ModFlared that's causing the multiplayer menu to crash when ViaFabricPlus is installed!

**Comment by FlorianMichael** [comment]
Alright, looking at the issue it seems that both ModFlared and ViaFabricPlus are modifying the same game code.

 I changed my mixin to use MixinExtras's `WrapOperation` which works with multiple mods having the same target; 

The mod author of ModFlared now also needs to replace their `Redirect` with `WrapOperation` in order to get both mods working. I would recommend opening an GitHub issue on their repository for this (https://github.com/HttpRafa/modflared).

My change: https://github.com/ViaVersion/ViaFabricPlus/commit/5b97f4fa6d2c9016f45031762a60968774941324
ModFlared code: https://github.com/HttpRafa/modflared/blob/multi/latest/common/src/main/java/de/rafael/modflared/mixin/client/MultiplayerServerListPingerMixin.java#L19


Thank you for reporting

**Comment by Gaming32** [comment]
Actually they don't need to replace it with `WrapOperation`. `WrapOperation` can wrap `Redirect` just fine. However, although not required, they should still switch to `WrapOperation` to increase compatibility with other mods.
