### ISSUE TITLE
Add the ability to join the new snapshot 24w33a from version 1.21

### ISSUE THREAD

**Issue by 74TTH** [ViaVersion/ViaFabricPlus#531]
### Problem Description

I would like to play on the new snapshot with my mod pack

### Solution Description

I'm not an expert in all this, but I would like to have such an opportunity

**Comment by FlorianMichael** [comment]
You will need to donate the 25 Dollar tier either here on https://github.com/sponsors/kennytv or on [patreon](https://www.patreon.com/kennytv) in order to get the ViaVersion/ViaBackwards versions that contain support for the snapshot. After you donated and got both jars you can put them into the `config/viafabricplus/jars` folder which is in the same location as your `mods` folder.

**Comment by 74TTH** [comment]
> Вам нужно будет пожертвовать уровень в 25 долларов либо здесь на https://github.com/sponsors/kennytv , либо на [patreon](https://www.patreon.com/kennytv) , чтобы получить версии ViaVersion/ViaBackwards, которые содержат поддержку снимка. После того, как вы пожертвовали и получили оба jar, вы можете поместить их в `config/viafabricplus/jars`папку, которая находится в том же месте, что и ваша `mods`папка.

At least tell me when this will be released to the public...

**Comment by Felix14-v2** [comment]
> At least tell me when this will be released to the public

After the 1.20.2 release, I guess

**Comment by FlorianMichael** [comment]
@74TTH A few days after the 1.21.2 release
