### ISSUE TITLE
ViaFabricPlus breaks Hypixel+ resource pack

### ISSUE THREAD

**Issue by Radk6** [ViaVersion/ViaFabricPlus#612]
### General Information

https://dump.viaversion.com/b89ea9cef781bd73e07e654d1fda300046b52d7ad375a55caed506887eeb77fb

### Bug Description

Joining Hypixel Skyblock with the Hypixel+ resource pack works fine without ViaFabricPlus, but setting the version to 1.8.x breaks it

### Steps to Reproduce

1. Download ViaFabricPlus, CIT Resewn and the Hypixel+ resource pack
2. Enable the pack
3. Join Hypixel and go to skyblock (the textures should work here)
4. Leave and set Hypixel's version to 1.8.x
5. Join Hypixel/skyblock again (now some/most of the textures should be missing)

### Expected Behavior

It should look like this:

![2024-11-11_12 29 19](https://github.com/user-attachments/assets/7aff3699-3492-4402-8c85-42e1d9e7a941)

But it looks like this:

![2024-11-11_12 28 59](https://github.com/user-attachments/assets/32259c30-f9aa-4335-a16e-4246e00822b5)

**Comment by FlorianMichael** [comment]
For what Minecraft version did you download the resource pack? Please make sure to install the 1.20 version

**Comment by Radk6** [comment]
> For what Minecraft version did you download the resource pack? Please make sure to install the 1.21 version

I used the latest version for 1.21.1

**Comment by FlorianMichael** [comment]
I would assume it's because Hypixel doesn't expect the player to have a 1.21 resourcepack installed (since you are joining as 1.8 player), Mojang often changed *a lot* on how resource packs works (hence why Hypixel+ also exists for multiple versions). 

ViaVersion projects generally don't handle these changes, so best for you would be to either just play as 1.21 client directly or to use a 1.8 client.
